### ISSUE TITLE
Circle 2.0 support

### ISSUE THREAD

**Issue by rshriram** [rainforestapp/circlemator#22]
Hi,
 I came across this repo. ITs pretty cool, and literally replaces some bots that we have to do these tasks. That said, we are using CircleCI 2.0. Which of the current features can be used with circle2.0 config file format (workflows, jobs, etc). 

Secondly, (naive question), is this codebase targeted only at Ruby apps? Will it work on a Go code base?

**Comment by shosti** [comment]
Hi! Most features should work out of the box, but the style check is currently only for ruby (because it uses rubocop). Theoretically it should be able to be extended to do anything that [pronto](https://github.com/prontolabs/pronto) supports, though (would require a little bit of tweaking).

In terms of CircleCI 2.0 support, the "build canceler" unfortunately doesn't work with workflows (afaik CircleCI doesn't have an API that will do that yet.) Everything else works well with workflows, though: you can just use the docker image as a job, e.g.:

```yaml
  style_check:
    docker:
      - image: rainforestapp/circlemator:latest
    steps:
      - checkout
      - run:
          name: Style check
          command: circlemator style-check --base-branch=develop
```

Let me know if you have any more questions.
